package org.lolhens.asmpatcher

import org.lolhens.asmpatcher.Opcode._
import org.objectweb.asm.Opcodes
import org.objectweb.asm.tree._

/**
 * Created by LolHens on 14.12.2014.
 */
class Opcode(val name: String,
             val opcode: Int,
             val optype: Int) {
  opcodes(opcode) = this

  override def toString = name

  def toInsn(args: String*): AbstractInsnNode = optype match {
    case AbstractInsnNode.INSN => new InsnNode(opcode)
    case AbstractInsnNode.INT_INSN => new IntInsnNode(opcode, args(0).toInt)
    case AbstractInsnNode.VAR_INSN => new VarInsnNode(opcode, args(0).toInt)
    case AbstractInsnNode.TYPE_INSN => ???
    case AbstractInsnNode.FIELD_INSN => ???
    case AbstractInsnNode.METHOD_INSN => ???
    case AbstractInsnNode.INVOKE_DYNAMIC_INSN =>
      throw new Exception("Found INVOKEDYNAMIC while reading");
    case AbstractInsnNode.JUMP_INSN => new JumpInsnNode(opcode, null) // args(0)
    case AbstractInsnNode.LDC_INSN => args(0) match {
      case cst if (cst == "*") => new LdcInsnNode(null)
      case cst if (cst.endsWith("\"")) => new LdcInsnNode(cst.substring(1, cst.length() - 1))
      case cst if (cst.endsWith("L")) => new LdcInsnNode(cst.substring(1, cst.length() - 1).toLong)
      case cst if (cst.endsWith("F")) => new LdcInsnNode(cst.substring(1, cst.length() - 1).toFloat)
      case cst if (cst.endsWith("D")) => new LdcInsnNode(cst.substring(1, cst.length() - 1).toDouble)
      case cst if (cst.contains(".")) => new LdcInsnNode(cst.toDouble)
      case cst => new LdcInsnNode(cst.toInt)
    }
    case AbstractInsnNode.IINC_INSN => new IincInsnNode(opcode, args(0).toInt)
    case AbstractInsnNode.LABEL => throw new Exception("Use L# for labels")
    case AbstractInsnNode.TABLESWITCH_INSN => ???
    case AbstractInsnNode.LOOKUPSWITCH_INSN => throw new Exception("I don't know how to deal with this insn type")
    case AbstractInsnNode.MULTIANEWARRAY_INSN => new MultiANewArrayInsnNode(args(0), args(1).toInt);
    case AbstractInsnNode.FRAME => throw new Exception("Use ClassWriter.COMPUTE_FRAMES");
    case _ => null
  }
}

object Opcode {
  private val opcodes = new Array[Opcode](255)

  def apply(opcode: Int): Opcode = opcodes(opcode)

  def apply(name: String): Opcode = {
    val opName = name.toLowerCase
    for (opcode <- opcodes) if (opcode.name == opName) return opcode
    null
  }

  val NOP = new Opcode("nop", Opcodes.NOP, AbstractInsnNode.INSN)
  val ACONST_NULL = new Opcode("aconst_null", Opcodes.ACONST_NULL, AbstractInsnNode.INSN)
  val ICONST_M1 = new Opcode("iconst_m1", Opcodes.ICONST_M1, AbstractInsnNode.INSN)
  val ICONST_0 = new Opcode("iconst_0", Opcodes.ICONST_0, AbstractInsnNode.INSN)
  val ICONST_1 = new Opcode("iconst_1", Opcodes.ICONST_1, AbstractInsnNode.INSN)
  val ICONST_2 = new Opcode("iconst_2", Opcodes.ICONST_2, AbstractInsnNode.INSN)
  val ICONST_3 = new Opcode("iconst_3", Opcodes.ICONST_3, AbstractInsnNode.INSN)
  val ICONST_4 = new Opcode("iconst_4", Opcodes.ICONST_4, AbstractInsnNode.INSN)
  val ICONST_5 = new Opcode("iconst_5", Opcodes.ICONST_5, AbstractInsnNode.INSN)
  val LCONST_0 = new Opcode("lconst_0", Opcodes.LCONST_0, AbstractInsnNode.INSN)
  val LCONST_1 = new Opcode("lconst_1", Opcodes.LCONST_1, AbstractInsnNode.INSN)
  val FCONST_0 = new Opcode("fconst_0", Opcodes.FCONST_0, AbstractInsnNode.INSN)
  val FCONST_1 = new Opcode("fconst_1", Opcodes.FCONST_1, AbstractInsnNode.INSN)
  val FCONST_2 = new Opcode("fconst_2", Opcodes.FCONST_2, AbstractInsnNode.INSN)
  val DCONST_0 = new Opcode("dconst_0", Opcodes.DCONST_0, AbstractInsnNode.INSN)
  val DCONST_1 = new Opcode("dconst_1", Opcodes.DCONST_1, AbstractInsnNode.INSN)
  val BIPUSH = new Opcode("bipush", Opcodes.BIPUSH, AbstractInsnNode.INT_INSN)
  val SIPUSH = new Opcode("sipush", Opcodes.SIPUSH, AbstractInsnNode.INT_INSN)
  val LDC = new Opcode("ldc", Opcodes.LDC, AbstractInsnNode.LDC_INSN)
  //val LDC_W = new Opcode("ldc_w", 19)
  //val LDC2_W = new Opcode("ldc2_w", 20)
  val ILOAD = new Opcode("iload", Opcodes.ILOAD, AbstractInsnNode.VAR_INSN)
  val LLOAD = new Opcode("lload", Opcodes.LLOAD, AbstractInsnNode.VAR_INSN)
  val FLOAD = new Opcode("fload", Opcodes.FLOAD, AbstractInsnNode.VAR_INSN)
  val DLOAD = new Opcode("dload", Opcodes.DLOAD, AbstractInsnNode.VAR_INSN)
  val ALOAD = new Opcode("aload", Opcodes.ALOAD, AbstractInsnNode.VAR_INSN)
  //val ILOAD_0 = new Opcode("iload_0", 26)
  //val ILOAD_1 = new Opcode("iload_1", 27)
  //val ILOAD_2 = new Opcode("iload_2", 28)
  //val ILOAD_3 = new Opcode("iload_3", 29)
  //val LLOAD_0 = new Opcode("lload_0", 30)
  //val LLOAD_1 = new Opcode("lload_1", 31)
  //val LLOAD_2 = new Opcode("lload_2", 32)
  //val LLOAD_3 = new Opcode("lload_3", 33)
  //val FLOAD_0 = new Opcode("fload_0", 34)
  //val FLOAD_1 = new Opcode("fload_1", 35)
  //val FLOAD_2 = new Opcode("fload_2", 36)
  //val FLOAD_3 = new Opcode("fload_3", 37)
  //val DLOAD_0 = new Opcode("dload_0", 38)
  //val DLOAD_1 = new Opcode("dload_1", 39)
  //val DLOAD_2 = new Opcode("dload_2", 40)
  //val DLOAD_3 = new Opcode("dload_3", 41)
  //val ALOAD_0 = new Opcode("aload_0", 42)
  //val ALOAD_1 = new Opcode("aload_1", 43)
  //val ALOAD_2 = new Opcode("aload_2", 44)
  //val ALOAD_3 = new Opcode("aload_3", 45)
  val IALOAD = new Opcode("iaload", Opcodes.IALOAD, AbstractInsnNode.INSN)
  val LALOAD = new Opcode("laload", Opcodes.LALOAD, AbstractInsnNode.INSN)
  val FALOAD = new Opcode("faload", Opcodes.FALOAD, AbstractInsnNode.INSN)
  val DALOAD = new Opcode("daload", Opcodes.DALOAD, AbstractInsnNode.INSN)
  val AALOAD = new Opcode("aaload", Opcodes.AALOAD, AbstractInsnNode.INSN)
  val BALOAD = new Opcode("baload", Opcodes.BALOAD, AbstractInsnNode.INSN)
  val CALOAD = new Opcode("caload", Opcodes.CALOAD, AbstractInsnNode.INSN)
  val SALOAD = new Opcode("saload", Opcodes.SALOAD, AbstractInsnNode.INSN)
  val ISTORE = new Opcode("istore", Opcodes.ISTORE, AbstractInsnNode.VAR_INSN)
  val LSTORE = new Opcode("lstore", Opcodes.LSTORE, AbstractInsnNode.VAR_INSN)
  val FSTORE = new Opcode("fstore", Opcodes.FSTORE, AbstractInsnNode.VAR_INSN)
  val DSTORE = new Opcode("dstore", Opcodes.DSTORE, AbstractInsnNode.VAR_INSN)
  val ASTORE = new Opcode("astore", Opcodes.ASTORE, AbstractInsnNode.VAR_INSN)
  //val ISTORE_0 = new Opcode("istore_0", 59)
  //val ISTORE_1 = new Opcode("istore_1", 60)
  //val ISTORE_2 = new Opcode("istore_2", 61)
  //val ISTORE_3 = new Opcode("istore_3", 62)
  //val LSTORE_0 = new Opcode("lstore_0", 63)
  //val LSTORE_1 = new Opcode("lstore_1", 64)
  //val LSTORE_2 = new Opcode("lstore_2", 65)
  //val LSTORE_3 = new Opcode("lstore_3", 66)
  //val FSTORE_0 = new Opcode("fstore_0", 67)
  //val FSTORE_1 = new Opcode("fstore_1", 68)
  //val FSTORE_2 = new Opcode("fstore_2", 69)
  //val FSTORE_3 = new Opcode("fstore_3", 70)
  //val DSTORE_0 = new Opcode("dstore_0", 71)
  //val DSTORE_1 = new Opcode("dstore_1", 72)
  //val DSTORE_2 = new Opcode("dstore_2", 73)
  //val DSTORE_3 = new Opcode("dstore_3", 74)
  //val ASTORE_0 = new Opcode("astore_0", 75)
  //val ASTORE_1 = new Opcode("astore_1", 76)
  //val ASTORE_2 = new Opcode("astore_2", 77)
  //val ASTORE_3 = new Opcode("astore_3", 78)
  val IASTORE = new Opcode("iastore", Opcodes.IASTORE, AbstractInsnNode.INSN)
  val LASTORE = new Opcode("lastore", Opcodes.LASTORE, AbstractInsnNode.INSN)
  val FASTORE = new Opcode("fastore", Opcodes.FASTORE, AbstractInsnNode.INSN)
  val DASTORE = new Opcode("dastore", Opcodes.DASTORE, AbstractInsnNode.INSN)
  val AASTORE = new Opcode("aastore", Opcodes.AASTORE, AbstractInsnNode.INSN)
  val BASTORE = new Opcode("bastore", Opcodes.BASTORE, AbstractInsnNode.INSN)
  val CASTORE = new Opcode("castore", Opcodes.CASTORE, AbstractInsnNode.INSN)
  val SASTORE = new Opcode("sastore", Opcodes.SASTORE, AbstractInsnNode.INSN)
  val POP = new Opcode("pop", Opcodes.POP, AbstractInsnNode.INSN)
  val POP2 = new Opcode("pop2", Opcodes.POP2, AbstractInsnNode.INSN)
  val DUP = new Opcode("dup", Opcodes.DUP, AbstractInsnNode.INSN)
  val DUP_X1 = new Opcode("dup_x1", Opcodes.DUP_X1, AbstractInsnNode.INSN)
  val DUP_X2 = new Opcode("dup_x2", Opcodes.DUP_X2, AbstractInsnNode.INSN)
  val DUP2 = new Opcode("dup2", Opcodes.DUP2, AbstractInsnNode.INSN)
  val DUP2_X1 = new Opcode("dup2_x1", Opcodes.DUP2_X1, AbstractInsnNode.INSN)
  val DUP2_X2 = new Opcode("dup2_x2", Opcodes.DUP2_X2, AbstractInsnNode.INSN)
  val SWAP = new Opcode("swap", Opcodes.SWAP, AbstractInsnNode.INSN)
  val IADD = new Opcode("iadd", Opcodes.IADD, AbstractInsnNode.INSN)
  val LADD = new Opcode("ladd", Opcodes.LADD, AbstractInsnNode.INSN)
  val FADD = new Opcode("fadd", Opcodes.FADD, AbstractInsnNode.INSN)
  val DADD = new Opcode("dadd", Opcodes.DADD, AbstractInsnNode.INSN)
  val ISUB = new Opcode("isub", Opcodes.ISUB, AbstractInsnNode.INSN)
  val LSUB = new Opcode("lsub", Opcodes.LSUB, AbstractInsnNode.INSN)
  val FSUB = new Opcode("fsub", Opcodes.FSUB, AbstractInsnNode.INSN)
  val DSUB = new Opcode("dsub", Opcodes.DSUB, AbstractInsnNode.INSN)
  val IMUL = new Opcode("imul", Opcodes.IMUL, AbstractInsnNode.INSN)
  val LMUL = new Opcode("lmul", Opcodes.LMUL, AbstractInsnNode.INSN)
  val FMUL = new Opcode("fmul", Opcodes.FMUL, AbstractInsnNode.INSN)
  val DMUL = new Opcode("dmul", Opcodes.DMUL, AbstractInsnNode.INSN)
  val IDIV = new Opcode("idiv", Opcodes.IDIV, AbstractInsnNode.INSN)
  val LDIV = new Opcode("ldiv", Opcodes.LDIV, AbstractInsnNode.INSN)
  val FDIV = new Opcode("fdiv", Opcodes.FDIV, AbstractInsnNode.INSN)
  val DDIV = new Opcode("ddiv", Opcodes.DDIV, AbstractInsnNode.INSN)
  val IREM = new Opcode("irem", Opcodes.IREM, AbstractInsnNode.INSN)
  val LREM = new Opcode("lrem", Opcodes.LREM, AbstractInsnNode.INSN)
  val FREM = new Opcode("frem", Opcodes.FREM, AbstractInsnNode.INSN)
  val DREM = new Opcode("drem", Opcodes.DREM, AbstractInsnNode.INSN)
  val INEG = new Opcode("ineg", Opcodes.INEG, AbstractInsnNode.INSN)
  val LNEG = new Opcode("lneg", Opcodes.LNEG, AbstractInsnNode.INSN)
  val FNEG = new Opcode("fneg", Opcodes.FNEG, AbstractInsnNode.INSN)
  val DNEG = new Opcode("dneg", Opcodes.DNEG, AbstractInsnNode.INSN)
  val ISHL = new Opcode("ishl", Opcodes.ISHL, AbstractInsnNode.INSN)
  val LSHL = new Opcode("lshl", Opcodes.LSHL, AbstractInsnNode.INSN)
  val ISHR = new Opcode("ishr", Opcodes.ISHR, AbstractInsnNode.INSN)
  val LSHR = new Opcode("lshr", Opcodes.LSHR, AbstractInsnNode.INSN)
  val IUSHR = new Opcode("iushr", Opcodes.IUSHR, AbstractInsnNode.INSN)
  val LUSHR = new Opcode("lushr", Opcodes.LUSHR, AbstractInsnNode.INSN)
  val IAND = new Opcode("iand", Opcodes.IAND, AbstractInsnNode.INSN)
  val LAND = new Opcode("land", Opcodes.LAND, AbstractInsnNode.INSN)
  val IOR = new Opcode("ior", Opcodes.IOR, AbstractInsnNode.INSN)
  val LOR = new Opcode("lor", Opcodes.LOR, AbstractInsnNode.INSN)
  val IXOR = new Opcode("ixor", Opcodes.IXOR, AbstractInsnNode.INSN)
  val LXOR = new Opcode("lxor", Opcodes.LXOR, AbstractInsnNode.INSN)
  val IINC = new Opcode("iinc", Opcodes.IINC, AbstractInsnNode.IINC_INSN)
  val I2L = new Opcode("i2l", Opcodes.I2L, AbstractInsnNode.INSN)
  val I2F = new Opcode("i2f", Opcodes.I2F, AbstractInsnNode.INSN)
  val I2D = new Opcode("i2d", Opcodes.I2D, AbstractInsnNode.INSN)
  val L2I = new Opcode("l2i", Opcodes.L2I, AbstractInsnNode.INSN)
  val L2F = new Opcode("l2f", Opcodes.L2F, AbstractInsnNode.INSN)
  val L2D = new Opcode("l2d", Opcodes.L2D, AbstractInsnNode.INSN)
  val F2I = new Opcode("f2i", Opcodes.F2I, AbstractInsnNode.INSN)
  val F2L = new Opcode("f2l", Opcodes.F2L, AbstractInsnNode.INSN)
  val F2D = new Opcode("f2d", Opcodes.F2D, AbstractInsnNode.INSN)
  val D2I = new Opcode("d2i", Opcodes.D2I, AbstractInsnNode.INSN)
  val D2L = new Opcode("d2l", Opcodes.D2L, AbstractInsnNode.INSN)
  val D2F = new Opcode("d2f", Opcodes.D2F, AbstractInsnNode.INSN)
  val I2B = new Opcode("i2b", Opcodes.I2B, AbstractInsnNode.INSN)
  val I2C = new Opcode("i2c", Opcodes.I2C, AbstractInsnNode.INSN)
  val I2S = new Opcode("i2s", Opcodes.I2S, AbstractInsnNode.INSN)
  val LCMP = new Opcode("lcmp", Opcodes.LCMP, AbstractInsnNode.INSN)
  val FCMPL = new Opcode("fcmpl", Opcodes.FCMPL, AbstractInsnNode.INSN)
  val FCMPG = new Opcode("fcmpg", Opcodes.FCMPG, AbstractInsnNode.INSN)
  val DCMPL = new Opcode("dcmpl", Opcodes.DCMPL, AbstractInsnNode.INSN)
  val DCMPG = new Opcode("dcmpg", Opcodes.DCMPG, AbstractInsnNode.INSN)
  val IFEQ = new Opcode("ifeq", Opcodes.IFEQ, AbstractInsnNode.JUMP_INSN)
  val IFNE = new Opcode("ifne", Opcodes.IFNE, AbstractInsnNode.JUMP_INSN)
  val IFLT = new Opcode("iflt", Opcodes.IFLT, AbstractInsnNode.JUMP_INSN)
  val IFGE = new Opcode("ifge", Opcodes.IFGE, AbstractInsnNode.JUMP_INSN)
  val IFGT = new Opcode("ifgt", Opcodes.IFGT, AbstractInsnNode.JUMP_INSN)
  val IFLE = new Opcode("ifle", Opcodes.IFLE, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPEQ = new Opcode("if_icmpeq", Opcodes.IF_ICMPEQ, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPNE = new Opcode("if_icmpne", Opcodes.IF_ICMPNE, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPLT = new Opcode("if_icmplt", Opcodes.IF_ICMPLT, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPGE = new Opcode("if_icmpge", Opcodes.IF_ICMPGE, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPGT = new Opcode("if_icmpgt", Opcodes.IF_ICMPGT, AbstractInsnNode.JUMP_INSN)
  val IF_ICMPLE = new Opcode("if_icmple", Opcodes.IF_ICMPLE, AbstractInsnNode.JUMP_INSN)
  val IF_ACMPEQ = new Opcode("if_acmpeq", Opcodes.IF_ACMPEQ, AbstractInsnNode.JUMP_INSN)
  val IF_ACMPNE = new Opcode("if_acmpne", Opcodes.IF_ACMPNE, AbstractInsnNode.JUMP_INSN)
  val GOTO = new Opcode("goto", Opcodes.GOTO, AbstractInsnNode.JUMP_INSN)
  val JSR = new Opcode("jsr", Opcodes.JSR, AbstractInsnNode.JUMP_INSN)
  val RET = new Opcode("ret", Opcodes.RET, AbstractInsnNode.VAR_INSN)
  val TABLESWITCH = new Opcode("tableswitch", Opcodes.TABLESWITCH, AbstractInsnNode.TABLESWITCH_INSN)
  val LOOKUPSWITCH = new Opcode("lookupswitch", Opcodes.LOOKUPSWITCH, AbstractInsnNode.LOOKUPSWITCH_INSN)
  val IRETURN = new Opcode("ireturn", Opcodes.IRETURN, AbstractInsnNode.INSN)
  val LRETURN = new Opcode("lreturn", Opcodes.LRETURN, AbstractInsnNode.INSN)
  val FRETURN = new Opcode("freturn", Opcodes.FRETURN, AbstractInsnNode.INSN)
  val DRETURN = new Opcode("dreturn", Opcodes.DRETURN, AbstractInsnNode.INSN)
  val ARETURN = new Opcode("areturn", Opcodes.ARETURN, AbstractInsnNode.INSN)
  val RETURN = new Opcode("return", Opcodes.RETURN, AbstractInsnNode.INSN)
  val GETSTATIC = new Opcode("getstatic", Opcodes.GETSTATIC, AbstractInsnNode.FIELD_INSN)
  val PUTSTATIC = new Opcode("putstatic", Opcodes.PUTSTATIC, AbstractInsnNode.FIELD_INSN)
  val GETFIELD = new Opcode("getfield", Opcodes.GETFIELD, AbstractInsnNode.FIELD_INSN)
  val PUTFIELD = new Opcode("putfield", Opcodes.PUTFIELD, AbstractInsnNode.FIELD_INSN)
  val INVOKEVIRTUAL = new Opcode("invokevirtual", Opcodes.INVOKEVIRTUAL, AbstractInsnNode.METHOD_INSN)
  val INVOKESPECIAL = new Opcode("invokespecial", Opcodes.INVOKESPECIAL, AbstractInsnNode.METHOD_INSN)
  val INVOKESTATIC = new Opcode("invokestatic", Opcodes.INVOKESTATIC, AbstractInsnNode.METHOD_INSN)
  val INVOKEINTERFACE = new Opcode("invokeinterface", Opcodes.INVOKEINTERFACE, AbstractInsnNode.METHOD_INSN)
  val INVOKEDYNAMIC = new Opcode("invokedynamic", Opcodes.INVOKEDYNAMIC, AbstractInsnNode.INVOKE_DYNAMIC_INSN)
  val NEW = new Opcode("new", Opcodes.NEW, AbstractInsnNode.TYPE_INSN)
  val NEWARRAY = new Opcode("newarray", Opcodes.NEWARRAY, AbstractInsnNode.INT_INSN)
  val ANEWARRAY = new Opcode("anewarray", Opcodes.ANEWARRAY, AbstractInsnNode.TYPE_INSN)
  val ARRAYLENGTH = new Opcode("arraylength", Opcodes.ARRAYLENGTH, AbstractInsnNode.INSN)
  val ATHROW = new Opcode("athrow", Opcodes.ATHROW, AbstractInsnNode.INSN)
  val CHECKCAST = new Opcode("checkcast", Opcodes.CHECKCAST, AbstractInsnNode.TYPE_INSN)
  val INSTANCEOF = new Opcode("instanceof", Opcodes.INSTANCEOF, AbstractInsnNode.TYPE_INSN)
  val MONITORENTER = new Opcode("monitorenter", Opcodes.MONITORENTER, AbstractInsnNode.INSN)
  val MONITOREXIT = new Opcode("monitorexit", Opcodes.MONITOREXIT, AbstractInsnNode.INSN)
  //val WIDE = new Opcode("wide", 196)
  val MULTIANEWARRAY = new Opcode("multianewarray", Opcodes.MULTIANEWARRAY, AbstractInsnNode.MULTIANEWARRAY_INSN)
  val IFNULL = new Opcode("ifnull", Opcodes.IFNULL, AbstractInsnNode.JUMP_INSN)
  val IFNONNULL = new Opcode("ifnonnull", Opcodes.IFNONNULL, AbstractInsnNode.JUMP_INSN)
  //val GOTO_W = new Opcode("goto_w", 200)
  //val JSR_W = new Opcode("jsr_w", 201)
  //val BREAKPOINT = new Opcode("breakpoint", 202)
  //val IMPDEP1 = new Opcode("impdep1", 254)
  //val IMPDEP2 = new Opcode("impdep2", 255)
}
